pipeline {
    agent any

    stages {
        stage ('build'){
            steps {
                git branch: 'main', url: 'https://github.com/Arvynrf/testing-java-maven.git'

                sh "mvn"
            }
        }
    }
}
